# Generated by Django 4.1.9 on 2023-06-03 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0003_book_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='Date',
        ),
    ]
